# Generated by roxytest: do not edit by hand!

# File R/maaslin2.R: @tests

test_that("Function run_maaslin2() @ L94", {
  # Def data paths
  metadata <- system.file("extdata", "reduced_meta.csv", package = "microfunk")
  file_path <-
    system.file("extdata", "reduced_genefam_cpm_kegg.tsv", package = "microfunk")
  
  # Read HUMAnN3 & MaAsLin2 Analysis
  da_result <-
    read_humann(file_path, metadata) %>%
    run_maaslin2(fixed_effects = "ARM")
  
  # Test number of significant associations
  da_result %>%
    dplyr::filter(signif == TRUE) %>%
    nrow() %>%
    testthat::expect_equal(63)
  
  # Test P-values
  da_result %>%
    dplyr::pull(p_value) %>%
    mean() %>%
    round(3) %>%
    testthat::expect_equal(0.538)
  
  # Test Q-values
  da_result %>%
    dplyr::pull(q_value) %>%
    mean() %>%
    round(3) %>%
    testthat::expect_equal(0.802)
})

