# Generated by roxytest: do not edit by hand!

# File R/humann_db.R: @tests

test_that("Function fetch_humann_db() @ L162", {
  # Remove existing file
  file.remove(file.path("~/.microfunk/humann_db", "test_v201901b.tsv.gz"))
  
  # Normal tests
  testthat::expect_invisible(fetch_humann_db("test"))
  testthat::expect_invisible(fetch_humann_db("test"))
  testthat::expect_error(fetch_humann_db("no_db"))
  testthat::expect_error(fetch_humann_db(version = "v201901a"))
  testthat::expect_invisible(fetch_humann_db("test", overwrite = TRUE))
  
  # Snapshot tests
  file.remove(file.path("~/.microfunk/humann_db", "test_v201901b.tsv.gz"))
  testthat::expect_snapshot(fetch_humann_db("test"))
  testthat::expect_snapshot(fetch_humann_db("test"))
  testthat::expect_snapshot(fetch_humann_db("test", overwrite = TRUE))
})

