# Generated by roxytest: do not edit by hand!

# File R/deseq2.R: @tests

test_that("Function run_deseq2() @ L83", {
  # Def data paths
  metadata <- system.file("extdata", "ex_meta.csv", package = "microfunk")
  file_path <-
    system.file("extdata", "All_genefam_rpk_kegg.tsv", package = "microfunk")
  
  # Read HUMAnN3 & DESeq2 Analysis
  da_result <-
    read_humann(file_path, metadata) %>%
    run_deseq2(factor = "ARM",
               test = "Wald",
               fitType = "local")
  
  # Test number of significant associations
  da_result %>%
    dplyr::filter(signif == TRUE) %>%
    nrow() %>%
    testthat::expect_equal(40)
  
  # Test P-values
  da_result %>%
    dplyr::pull(pvalue) %>%
    mean() %>%
    round(3) %>%
    testthat::expect_equal(0.557)
  
  # Test P-adjusted values
  da_result %>%
    dplyr::pull(padj) %>%
    mean(na.rm = TRUE) %>%
    round(3) %>%
    testthat::expect_equal(0.858)
})

