# Generated by roxytest: do not edit by hand!

# File R/read_humann.R: @tests

test_that("Function read_humann() @ L60", {
  file_c <-
    system.file("extdata", "All_genefam_cpm_kegg.tsv", package =
    "microfunk")
  metadata <-
    system.file("extdata", "ex_meta.csv", package =
    "microfunk")
  file_r <-
    system.file("extdata", "All_genefam_rpk_kegg.tsv",
    package = "microfunk")
  
  # Test metadata errors
  system.file("extdata", package = "microfunk") %>%
    list.files(pattern = "ex_meta_error", full.names = TRUE) %>%
    purrr::walk(~testthat::expect_error(read_humann(file_c, .x)))
  
  # Test HUMAnN3 file errors
  system.file("extdata", package = "microfunk") %>%
    list.files(pattern = "All_genefam_cpm_kegg_error", full.names = TRUE) %>%
    purrr::walk(~ testthat::expect_error(read_humann(.x, metadata)))
  
  # Test output
  testthat::expect_equal(class(read_humann(file_r, metadata))[1],
    "SummarizedExperiment")
})


test_that("Function .humann_path_checks() @ L122", {
  nfile <-
    system.file("extdata", "nfile", package = "microfunk")
  meta <-
    system.file("extdata", "ex_meta.csv", package = "microfunk")
  file <-
    system.file("extdata", "All_genefam_cpm_kegg.tsv", package = "microfunk")
  
  testthat::expect_error(.humann_path_checks(metadata = meta))
  testthat::expect_error(.humann_path_checks(file))
  testthat::expect_error(.humann_path_checks(nfile, meta))
})

