# Generated by roxytest: do not edit by hand!

# File R/read_gfam.R: @tests

test_that("Function read_gfam() @ L22", {
  file_path <-
    system.file("extdata", "demo_genefamilies.tsv", package = "microfunk")
  
  # Test output has tree columns
  testthat::expect_equal(ncol(read_gfam(file_path)), 3)
})

