# Generated by roxytest: do not edit by hand!

# File R/norm_abundance.R: @tests

test_that("Function norm_abundance() @ L88", {
  # Sample RPK testing data
  column1 <- c("FIRST", "FIRST|Species1", "UNGROUPED","UNGROUPED|Species1", "UNGROUPED|Species2", "UNMAPPED")
  column2 <- c(5, 5, 100, 90, 10, 20)
  rpk_data <- tibble::tibble(
   function_id = column1,
   sample1 = column2,
   sample2 = column2 ) %>%
   data.frame(row.names = 1)
  
  # Sample RPK SE object
  rpk_se <-
   SummarizedExperiment::SummarizedExperiment(assays = list(humann = rpk_data))
  
  # Sample relative abundance testing data
  relab_data <- rpk_data %>%
    dplyr::mutate(dplyr::across(dplyr::where(is.numeric), ~ .x / 125))
  
  # Sample relative abundance SE object
  relab_se <-
   SummarizedExperiment::SummarizedExperiment(assays = list(humann = relab_data))
  
  # Sample CPM testing data
  cpm_data <- relab_data %>%
    dplyr::mutate(dplyr::across(dplyr::where(is.numeric), ~ .x * 1e6))
  
  # Sample CPM SE object
  cpm_se <-
   SummarizedExperiment::SummarizedExperiment(assays = list(humann = cpm_data))
  
  # Test errors
  testthat::expect_error(norm_abundance(rpk_se, norm = "unsupported"))
  testthat::expect_error(norm_abundance(cpm_se, norm = "cpm"))
  testthat::expect_error(norm_abundance(relab_se, norm = "relab"))
  
  # Test outputs
  inputs <- list(
    list(rpk_se, "cpm"),
    list(rpk_se, "relab"),
    list(cpm_se, "relab"),
    list(relab_se, "cpm")
  )
  expected_outputs <- list(
    cpm_se,
    relab_se,
    relab_se,
    cpm_se
  )
  
  purrr::walk2(inputs, expected_outputs, ~ {
    testthat::expect_equal(norm_abundance(.x[[1]], .x[[2]]), .y)
  })
})


test_that("Function .extract_norm_method() @ L158", {
  se <- read_humann(
   file_path = system.file("extdata", "cpm_kegg_error_units.tsv", package = "microfunk"),
   metadata = system.file("extdata", "meta_error_units.csv", package = "microfunk")
  )
   data <- SummarizedExperiment::assays(se)$humann %>%
     tibble::as_tibble(rownames = "function_id")
   testthat::expect_error(.extract_norm_method(data))
})


test_that("Function .rpk2cpm() @ L216", {
  # Input tibble
  column1 <- c("UNMAPPED", "UNGROUPED", "UNGROUPED|Species1", "UNGROUPED|Species2", "FIRST", "FIRST|Species1")
  column2 <- c(20, 100, 90, 10, 5, 5)
  input_tbl <- tibble::tibble(
    function_id = column1,
    sample1 = column2,
    sample2 = column2 )
  
  # Expected output tibble
  column1 <- c("FIRST", "FIRST|Species1", "UNGROUPED","UNGROUPED|Species1", "UNGROUPED|Species2", "UNMAPPED")
  column2 <- c(40000, 40000, 800000, 720000, 80000, 160000)
  output_tbl <- tibble::tibble(
    function_id = column1,
    sample1 = column2,
    sample2 = column2 ) %>%
    data.frame(row.names = 1)
  
  testthat::expect_equal(.rpk2cpm(input_tbl), output_tbl)
})


test_that("Function .relab2cpm() @ L272", {
  # Input tibble
  column1 <- c("UNMAPPED", "UNGROUPED", "UNGROUPED|Species1", "UNGROUPED|Species2", "FIRST", "FIRST|Species1")
  column2 <- c(0.16, 0.8, 0.72, 0.08, 0.04, 0.04)
  input_tbl <- tibble::tibble(
    function_id = column1,
    sample1 = column2,
    sample2 = column2 )
  
  # Expected output tibble
  column1 <- c("FIRST", "FIRST|Species1", "UNGROUPED","UNGROUPED|Species1", "UNGROUPED|Species2", "UNMAPPED")
  column2 <- c(40000, 40000, 800000, 720000, 80000, 160000)
  output_tbl <- tibble::tibble(
    function_id = column1,
    sample1 = column2,
    sample2 = column2 ) %>%
    data.frame(row.names = 1)
  
  testthat::expect_equal(.relab2cpm(input_tbl), output_tbl)
})


test_that("Function .rpk2relab() @ L329", {
  # Input tibble
  column1 <- c("UNMAPPED", "UNGROUPED", "UNGROUPED|Species1", "UNGROUPED|Species2", "FIRST", "FIRST|Species1")
  column2 <- c(20, 100, 90, 10, 5, 5)
  input_tbl <- tibble::tibble(
    function_id = column1,
    sample1 = column2,
    sample2 = column2 )
  
  # Expected output tibble
  column1 <- c("FIRST", "FIRST|Species1", "UNGROUPED","UNGROUPED|Species1", "UNGROUPED|Species2", "UNMAPPED")
  column2 <- c(0.04, 0.04, 0.8, 0.72, 0.08, 0.16)
  output_tbl <- tibble::tibble(
    function_id = column1,
    sample1 = column2,
    sample2 = column2 ) %>%
    data.frame(row.names = 1)
  
  testthat::expect_equal(.rpk2relab(input_tbl), output_tbl)
})


test_that("Function .cpm2relab() @ L386", {
  # Input tibble
  column1 <- c("UNMAPPED", "UNGROUPED", "UNGROUPED|Species1", "UNGROUPED|Species2", "FIRST", "FIRST|Species1")
  column2 <- c(160000, 800000, 720000, 80000, 40000, 40000)
  input_tbl <- tibble::tibble(
    function_id = column1,
    sample1 = column2,
    sample2 = column2 )
  
  # Expected output tibble
  column1 <- c("FIRST", "FIRST|Species1", "UNGROUPED","UNGROUPED|Species1", "UNGROUPED|Species2", "UNMAPPED")
  column2 <- c(0.04, 0.04, 0.8, 0.72, 0.08, 0.16)
  output_tbl <- tibble::tibble(
    function_id = column1,
    sample1 = column2,
    sample2 = column2 ) %>%
    data.frame(row.names = 1)
  
  testthat::expect_equal(.cpm2relab(input_tbl), output_tbl)
})

