# Generated by roxytest: do not edit by hand!

# File R/humann_regroup.R: @tests

test_that("Function humann_regroup() @ L52", {
  se_regrouped <- read_humann(
   file_path = system.file("extdata", "reduced_genefam_rpk_uniref.tsv", package = "microfunk"),
   metadata = system.file("extdata", "reduced_meta.csv", package = "microfunk")
   ) %>%
   humann_regroup(to = "test")
  
  # Test output
  testthat::expect_equal(class(se_regrouped)[1],
    "SummarizedExperiment")
})


test_that("Function .check_regroup() @ L123", {
  # Test SE annotation errors
  meta <-  system.file("extdata", "reduced_meta.csv", package = "microfunk")
  se_list <- system.file("extdata", package = "microfunk") %>%
   list.files(pattern = "reduced_genefam_rpk_uniref_error", full.names = TRUE) %>%
     purrr::map(~ read_humann(.x, meta))
   purrr::walk(se_list, ~ testthat::expect_error(.check_regroup(.x, to = "test")))
  
  # Test invalid annotation requested
  se <- read_humann(
   file_path = system.file("extdata", "reduced_genefam_rpk_uniref.tsv", package = "microfunk"),
   metadata = meta
   )
   testthat::expect_error(.check_regroup(se, to = "abc"))
})

