# Generated by roxytest: do not edit by hand!

# File R/read_humann.R: @tests

test_that("Function read_genefamily() @ L36", {
  # Test errors
  system.file("extdata", package = "microfunk") %>%
    list.files(pattern = "demo_genefamilies_error", full.names = TRUE) %>%
    purrr::walk(~ testthat::expect_error(read_genefamily(.x)))
  
  # Test normal file
  norm_file <-
   system.file("extdata", package = "microfunk") %>%
   list.files(pattern = "demo_genefamilies-cpm", full.names = TRUE) %>%
   read_genefamily()
  
  testthat::expect_equal(colnames(norm_file)[3], "cpm")
})

