# Generated by roxytest: do not edit by hand!

# File R/plt_volcano.R: @tests

test_that("Function plt_volcano() @ L61", {
  # Def data paths
  metadata <- system.file("extdata", "ex_meta.csv", package = "microfunk")
  file_path <- system.file("extdata", "All_genefam_cpm_kegg.tsv", package = "microfunk")
  
  # Read HUMAnN3 & MaAsLin2 Analysis
  da_result <-
    read_humann(file_path, metadata) %>%
    run_maaslin2(fixed_effects = "ARM")
  
  # Volcano Plot
  plt <- plt_volcano(da_result)
  
  # Check ggplot object
  testthat::expect_true("ggplot" %in% class(plt))
  
  # Check number of layers
  testthat::expect_equal(length(plt$layers), 4)
  
  # Check labels
  labels <- c("coefficient", "-log10 p-value", "coefficient sign", "q-value",
              "yintercept", "xintercept", "feature")
  
  testthat::expect_equal(labels, unname(unlist(plt$labels)))
})

