# Generated by roxytest: do not edit by hand!

# File R/maaslin2.R: @tests

test_that("Function run_maaslin2() @ L95", {
  # Def data paths
  metadata <- system.file("extdata", "reduced_meta.csv", package = "microfunk")
  file_path <- system.file("extdata", "reduced_genefam_cpm_kegg.tsv", package = "microfunk")
  
  # Read HUMAnN3
  result <- read_humann(file_path, metadata)
  
  # MaAsLin2 Analysis
  run_maaslin2(se = result, fixed_effects = "ARM")
  
  # Test number of significant associations
  output <- paste0(tempdir(), "/output_folder/significant_results.tsv") %>%
   data.table::fread() %>%
   tibble::as_tibble()
  
  testthat::expect_equal(nrow(output), 5)
  
  # Test P-values
  pval <- output %>%
   dplyr::select(pval) %>%
   colSums()
  testthat::expect_equal(as.numeric(round(pval, 5)), 0.00032)
  
  # Test Q-values
  qval <- output %>%
   dplyr::select(qval) %>%
   colSums()
  testthat::expect_equal(as.numeric(round(qval, 2)), 0.35)
})

