# Generated by roxytest: do not edit by hand!

# File R/metagenomeSeq.R: @tests

test_that("Function run_metagenomeseq() @ L89", {
  # Read HUMAnN3 & MetagenomeSeq Analysis (FitZig)
  da_fitzig <- read_humann(
    file_path = system.file("extdata", "All_genefam_cpm_kegg.tsv", package = "microfunk"),
    metadata = system.file("extdata", "ex_meta.csv", package = "microfunk")
   ) %>% run_metagenomeseq(variable = "ARM")
  
  # Test name of features returned
  n_zig <- c("K07488", "K09805", "K00863", "K02977", "K11905", "K00263", "K00737",
             "K11904", "K09961", "K22902")
  f_zig <- as.vector(da_fitzig$function_id)
  testthat::expect_equal(n_zig, f_zig)
  
  # Test p-values
  da_fitzig %>%
   dplyr::pull(adjPvalues) %>%
   mean() %>%
   round(3) %>%
  testthat::expect_equal(0.027)
  
  # Read HUMAnN3 & MetagenomeSeq Analysis (FitFeatureModel)
  da_fitfeature <- read_humann(
    file_path = system.file("extdata", "All_genefam_cpm_kegg.tsv", package = "microfunk"),
    metadata = system.file("extdata", "ex_meta.csv", package = "microfunk")
   ) %>% run_metagenomeseq(model = "fitFeatureModel", variable = "ARM")
  
  # Test name of features returned
  n_feature <- c("K03300", "K16951", "K00135", "K07488", "K06015", "K06196",
                 "K01908", "K19130", "K01060", "K09858")
  f_feature <- as.vector(da_fitfeature$function_id)
  testthat::expect_equal(n_feature, f_feature)
  
  # Test p-values
  da_fitfeature %>%
   dplyr::pull(adjPvalues) %>%
   mean() %>%
   round(3) %>%
  testthat::expect_equal(0.258)
})

