# Generated by roxytest: do not edit by hand!

# File R/da_homogenization.R: @tests

test_that("Function .da_homogenization() @ L38", {
  # Def file paths
  file_path = system.file("extdata", "reduced_genefam_cpm_kegg.tsv", package = "microfunk")
  metadata = system.file("extdata", "reduced_meta.csv", package = "microfunk")
  
  # Read HUMAnN3 & DA Analysis
  da_deseq <- read_humann(file_path, metadata) %>%
   run_deseq2(factor = "ARM")
  da_maaslin <- read_humann(file_path, metadata) %>%
   run_maaslin2(fixed_effects = "ARM")
  
   # Test column names
   n <- c("feature", "metadata", "da_method", "coefficient", "log2FC", "stderr",
          "lfc_stderr", "p_value", "q_value", "padj_value", "signif")
  
   testthat::expect_equal(n, colnames(da_deseq))
   testthat::expect_equal(n, colnames(da_maaslin))
  
   # Check unknown input type
   da_unknown <- tibble::tibble(x = 1:10, y = 1:10)
   testthat::expect_error(.da_homogenization(da_unknown))
})

