# Generated by roxyglobals: do not edit by hand

utils::globalVariables(c(
  # <plt_lollipop>
  ".",
  # <plt_lollipop>
  # <plt_volcano>
  "coef",
  # <plt_lollipop>
  # <plt_volcano>
  "feature",
  # <run_maaslin2>
  # <.create_MRexp>
  # <.extract_norm_method>
  # <.rpk2cpm>
  # <.relab2cpm>
  # <.rpk2relab>
  # <.cpm2relab>
  # <read_humann>
  "function_id",
  # <run_maaslin2>
  # <.maaslin2_quietly>
  "heatmap_firt_n",
  # <plt_lollipop>
  # <plt_volcano>
  "pval",
  # <plt_lollipop>
  # <plt_volcano>
  "qval",
  NULL
))
